## system
server:
  port: 8080


spring:
  ## dataSource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://59.110.142.126/mybegin?characterEncoding=utf-8&useSSL=false
    username: root
    password: Iamgpj1996.mysql
  ## spring data jpa
  jpa:
      show-sql: true

  ## 163 email
  mail:
    host: smtp.163.com
    username: iamgpj@163.com
    password: auth163

  ## redis
  redis:
    host: 127.0.0.1
    port: 6379



##
thirdparty-platform:
  qq:
    appId: 101422018
    appSecret: 9974d4424ccc4655169407638dd570d0
    redirectUrl: http://iamgpj.com/callback




